/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /healthz` `OpenAPI` path (served by the Serenade HTTP front controller). */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /openapi.json` `OpenAPI` path (served by the Serenade HTTP front controller). */
        get: operations["openapi_json"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/ai/tools` `OpenAPI` stub (shop scope only). */
        get: operations["list_shop_ai_tools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /v1/carts` `OpenAPI` path (served by the Serenade HTTP front controller). */
        post: operations["create_cart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/carts/{id}` `OpenAPI` path (served by the Serenade HTTP front controller). */
        get: operations["get_cart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/{id}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /v1/carts/{id}/lines` `OpenAPI` path (served by the Serenade HTTP front controller). */
        post: operations["add_cart_line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/{id}/lines/{line_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** `DELETE /v1/carts/{id}/lines/{line_id}` `OpenAPI` path (served by the Serenade HTTP front controller). */
        delete: operations["delete_cart_line"];
        options?: never;
        head?: never;
        /** `PATCH /v1/carts/{id}/lines/{line_id}` `OpenAPI` path (served by the Serenade HTTP front controller). */
        patch: operations["update_cart_line"];
        trace?: never;
    };
    "/v1/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /v1/checkout` `OpenAPI` path (served by the Serenade HTTP front controller). */
        post: operations["place_order"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/products` `OpenAPI` path (served by the Serenade HTTP front controller). */
        get: operations["list_products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/products/{id}` `OpenAPI` path (served by the Serenade HTTP front controller). */
        get: operations["get_product"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/ai/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/{admin_api_prefix}/ai/tools` `OpenAPI` stub. */
        get: operations["list_ai_tools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/{admin_api_prefix}/orders` `OpenAPI` path (Serenade front). */
        get: operations["list_admin_orders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** `PATCH /v1/{admin_api_prefix}/orders/{id}` `OpenAPI` path (Serenade front). */
        patch: operations["patch_admin_order"];
        trace?: never;
    };
    "/v1/{admin_api_prefix}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/{admin_api_prefix}/products` `OpenAPI` path (Serenade front). */
        get: operations["list_admin_products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/sandbox/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/{admin_api_prefix}/sandbox/audit` `OpenAPI` stub. */
        get: operations["list_sandbox_audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/sandbox/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /v1/{admin_api_prefix}/sandbox/jobs` `OpenAPI` stub. */
        post: operations["create_sandbox_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/sandbox/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/{admin_api_prefix}/sandbox/jobs/{id}` `OpenAPI` stub. */
        get: operations["get_sandbox_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Body for `POST /v1/carts/{id}/lines`. */
        AddCartLineRequest: {
            /**
             * Format: int32
             * @description Quantity greater than zero.
             */
            quantity: number;
            /** @description Variant to add. */
            variant_id: string;
        };
        /** @description One tool row for agent discovery (shop or admin). */
        AiToolResponse: {
            /** @description Read / draft write / commit (`read` / `draft_write` / `commit`). */
            effect: string;
            /** @description Autonomous agents need human or strict policy approve. */
            human_approve_for_autonomous: boolean;
            /** @description HTTP method for the commerce route. */
            method: string;
            /** @description Stable MCP / agent function name. */
            name: string;
            /** @description Matching `OpenAPI` path template. */
            openapi_path: string;
            /** @description Shop vs admin authz class (`shop` / `admin`). */
            scope: string;
            /** @description One-line capability summary. */
            summary: string;
        };
        /** @description Cart line JSON. */
        CartLineResponse: {
            /** @description Line id. */
            id: string;
            /** @description Line total (`unit_price × quantity`). */
            line_total: components["schemas"]["MoneyResponse"];
            /** @description Snapshotted product name. */
            product_name: string;
            /**
             * Format: int32
             * @description Quantity.
             */
            quantity: number;
            /** @description Snapshotted unit price. */
            unit_price: components["schemas"]["MoneyResponse"];
            /** @description Variant id. */
            variant_id: string;
            /** @description Snapshotted SKU. */
            variant_sku: string;
        };
        /** @description Cart JSON including recalculated totals. */
        CartResponse: {
            /** @description Cart currency. */
            currency: string;
            /** @description Optional customer id. */
            customer_id?: string | null;
            /** @description Cart id. */
            id: string;
            /** @description Sum of line totals. */
            items_total: components["schemas"]["MoneyResponse"];
            /** @description Cart lines. */
            lines: components["schemas"]["CartLineResponse"][];
            /** @description Cart status (`open` or `checked_out`). */
            status: string;
            /** @description Session token. */
            token: string;
        };
        /** @description Body for `POST /v1/checkout`. */
        CheckoutRequest: {
            /** @description Cart to convert into an order. */
            cart_id: string;
        };
        /** @description Body for `POST /v1/carts`. */
        CreateCartRequest: {
            /** @description ISO currency for the cart (default `EUR`). */
            currency?: string | null;
        };
        /** @description Request body for creating a sandbox job. */
        CreateSandboxJobRequest: {
            /** @description Cart currency for the quote fixture. */
            currency: string;
            /** @description Job type (`quote` only). */
            job_type: string;
            /** @description Cart lines for the guest snapshot. */
            lines: components["schemas"]["SandboxJobLine"][];
        };
        /** @description JSON error body (message + stable machine code). */
        ErrorBody: {
            /** @description Stable machine-readable code (`not_found`, `conflict`, …). */
            code: string;
            /** @description Human-readable error message. */
            error: string;
        };
        /** @description JSON body for `GET /healthz`. */
        HealthResponse: {
            /** @description Serenade kernel integration marker from the `rustashop` crate (`serenade` after boot). */
            kernel: string;
            /** @description Liveness status. */
            status: string;
        };
        /** @description Money JSON for cart responses. */
        MoneyResponse: {
            /**
             * Format: int64
             * @description Amount in minor units.
             */
            amount_minor: number;
            /** @description ISO currency code. */
            currency: string;
        };
        /** @description Order line JSON. */
        OrderLineResponse: {
            /** @description Line id. */
            id: string;
            /** @description Snapshotted line total. */
            line_total: components["schemas"]["MoneyResponse"];
            /** @description Snapshotted product name. */
            product_name: string;
            /**
             * Format: int32
             * @description Quantity.
             */
            quantity: number;
            /** @description Snapshotted unit price. */
            unit_price: components["schemas"]["MoneyResponse"];
            /** @description Variant id when still known. */
            variant_id?: string | null;
            /** @description Snapshotted SKU. */
            variant_sku: string;
        };
        /** @description Paginated admin order list. */
        OrderListResponse: {
            /** @description Orders newest first. */
            items: components["schemas"]["OrderResponse"][];
        };
        /** @description Order JSON returned by checkout. */
        OrderResponse: {
            /** @description Source cart id. */
            cart_id?: string | null;
            /** @description Order currency. */
            currency: string;
            /** @description Order id. */
            id: string;
            /** @description Sum of line totals. */
            items_total: components["schemas"]["MoneyResponse"];
            /** @description Order lines. */
            lines: components["schemas"]["OrderLineResponse"][];
            /** @description Human-readable number. */
            number: string;
            /** @description Payment status (`pending` at checkout; no provider attached yet). */
            payment_status: string;
            /** @description Fulfillment state. */
            state: string;
            /** @description Payable total. */
            total: components["schemas"]["MoneyResponse"];
        };
        /** @description Body for admin order status PATCH. */
        PatchOrderStatusRequest: {
            /** @description Fulfillment status: `placed`, `paid`, `shipped`, or `cancelled`. */
            status: string;
        };
        /** @description Product detail including purchasable variants. */
        ProductDetailResponse: {
            /** @description Optional category id. */
            category_id?: string | null;
            /** @description Optional long description. */
            description?: string | null;
            /** @description Whether the product is offered for sale. */
            enabled: boolean;
            /** @description Stable identifier. */
            id: string;
            /** @description Display name. */
            name: string;
            /** @description Unique URL slug. */
            slug: string;
            /** @description Purchasable SKUs for this product. */
            variants: components["schemas"]["ProductVariantResponse"][];
        };
        /** @description List payload for `GET /v1/products`. */
        ProductListResponse: {
            /** @description Page of products. */
            items: components["schemas"]["ProductResponse"][];
        };
        /** @description Product JSON returned by list routes (no variants). */
        ProductResponse: {
            /** @description Optional category id. */
            category_id?: string | null;
            /** @description Optional long description. */
            description?: string | null;
            /** @description Whether the product is offered for sale. */
            enabled: boolean;
            /** @description Stable identifier. */
            id: string;
            /** @description Display name. */
            name: string;
            /** @description Unique URL slug. */
            slug: string;
        };
        /** @description Variant JSON nested under product detail. */
        ProductVariantResponse: {
            /** @description Stable identifier. */
            id: string;
            /** @description Optional variant label. */
            name?: string | null;
            /** @description Unit price. */
            price: components["schemas"]["MoneyResponse"];
            /** @description Parent product id. */
            product_id: string;
            /** @description Unique stock-keeping unit. */
            sku: string;
            /**
             * Format: int32
             * @description Available stock quantity.
             */
            stock_quantity: number;
        };
        /** @description Adjustment JSON for admin. */
        SandboxAdjustmentResponse: {
            /**
             * Format: int64
             * @description Signed minor units.
             */
            amount_minor: number;
            /** @description Currency. */
            currency: string;
            /** @description Label. */
            label: string;
        };
        /** @description One audit row (process-local until a persist table lands). */
        SandboxAuditRecord: {
            /** @description Actor label (`admin-bearer` when authorized). */
            actor: string;
            /**
             * Format: int64
             * @description Unix seconds when the job was created.
             */
            created_at_unix: number;
            /** @description Job id. */
            job_id: string;
            /** @description Job type. */
            job_type: string;
            /** @description Source fingerprint. */
            source_hash: string;
            /** @description Final status string. */
            status: string;
        };
        /** @description One cart line in the create-job body. */
        SandboxJobLine: {
            /**
             * Format: int32
             * @description Quantity.
             */
            quantity: number;
            /** @description SKU. */
            sku: string;
            /**
             * Format: int64
             * @description Unit price in minor units.
             */
            unit_price_minor: number;
        };
        /** @description Public job view. */
        SandboxJobResponse: {
            /** @description Host-validated adjustments when succeeded. */
            adjustments?: components["schemas"]["SandboxAdjustmentResponse"][] | null;
            /** @description Error message when failed. */
            error?: string | null;
            /** @description Job id. */
            id: string;
            /** @description Job type. */
            job_type: string;
            /** @description Fingerprint of the fixture source used. */
            source_hash: string;
            /** @description Lifecycle status. */
            status: components["schemas"]["SandboxJobStatus"];
        };
        /**
         * @description Job status returned to the admin UI.
         * @enum {string}
         */
        SandboxJobStatus: "running" | "succeeded" | "failed";
        /** @description Body for `PATCH /v1/carts/{id}/lines/{line_id}`. */
        UpdateCartLineRequest: {
            /**
             * Format: int32
             * @description Replacement quantity greater than zero.
             */
            quantity: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    openapi_json: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_shop_ai_tools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shop-scoped commerce AI tool catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiToolResponse"][];
                };
            };
        };
    };
    create_cart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCartRequest"];
            };
        };
        responses: {
            /** @description Cart created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Invalid currency */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_cart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cart id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Unknown id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    add_cart_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cart id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCartLineRequest"];
            };
        };
        responses: {
            /** @description Cart after add */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Unknown cart or variant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid quantity or currency */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_cart_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cart id */
                id: string;
                /** @description Line id */
                line_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart after delete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Unknown cart or line */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_cart_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cart id */
                id: string;
                /** @description Line id */
                line_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartLineRequest"];
            };
        };
        responses: {
            /** @description Cart after update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Unknown cart or line */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid quantity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    place_order: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replay token */
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Order placed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Unknown cart */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Cart already checked out */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Empty cart */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_products: {
        parameters: {
            query?: {
                /** @description Maximum rows (capped). */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
        };
    };
    get_product: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product with variants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailResponse"];
                };
            };
            /** @description Unknown id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_ai_tools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commerce AI tool catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiToolResponse"][];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_admin_orders: {
        parameters: {
            query?: {
                /** @description Maximum rows (capped). */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    patch_admin_order: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchOrderStatusRequest"];
            };
        };
        responses: {
            /** @description Updated order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid status */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_admin_products: {
        parameters: {
            query?: {
                /** @description Maximum rows (capped). */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_sandbox_audit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit rows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxAuditRecord"][];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_sandbox_job: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSandboxJobRequest"];
            };
        };
        responses: {
            /** @description Job accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxJobResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_sandbox_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxJobResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unknown job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
