/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /healthz` `OpenAPI` path (served by the Serenade HTTP front controller). */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /openapi.json` `OpenAPI` path (served by the Serenade HTTP front controller). */
        get: operations["openapi_json"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ai/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/ai/tools` `OpenAPI` stub (shop scope only). */
        get: operations["list_shop_ai_tools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /v1/carts` `OpenAPI` path (served by the Serenade HTTP front controller). */
        post: operations["create_cart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/carts/{id}` `OpenAPI` path (served by the Serenade HTTP front controller). */
        get: operations["get_cart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/{id}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /v1/carts/{id}/lines` `OpenAPI` path (served by the Serenade HTTP front controller). */
        post: operations["add_cart_line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/{id}/lines/{line_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** `DELETE /v1/carts/{id}/lines/{line_id}` `OpenAPI` path (served by the Serenade HTTP front controller). */
        delete: operations["delete_cart_line"];
        options?: never;
        head?: never;
        /** `PATCH /v1/carts/{id}/lines/{line_id}` `OpenAPI` path (served by the Serenade HTTP front controller). */
        patch: operations["update_cart_line"];
        trace?: never;
    };
    "/v1/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /v1/checkout` `OpenAPI` path (served by the Serenade HTTP front controller). */
        post: operations["place_order"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/products` `OpenAPI` path (served by the Serenade HTTP front controller). */
        get: operations["list_products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/products/{id}` `OpenAPI` path (served by the Serenade HTTP front controller). */
        get: operations["get_product"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/ai/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `OpenAPI` stub: list provider status. */
        get: operations["list_ai_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/ai/providers/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `OpenAPI` stub: static catalog. */
        get: operations["list_ai_providers_catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/ai/providers/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `OpenAPI` stub: test provider. */
        post: operations["test_ai_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/ai/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/{admin_api_prefix}/ai/tools` `OpenAPI` stub. */
        get: operations["list_ai_tools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/{admin_api_prefix}/orders` `OpenAPI` path (Serenade front). */
        get: operations["list_admin_orders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** `PATCH /v1/{admin_api_prefix}/orders/{id}` `OpenAPI` path (Serenade front). */
        patch: operations["patch_admin_order"];
        trace?: never;
    };
    "/v1/{admin_api_prefix}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/{admin_api_prefix}/products` `OpenAPI` path (Serenade front). */
        get: operations["list_admin_products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/sandbox/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/{admin_api_prefix}/sandbox/audit` `OpenAPI` stub. */
        get: operations["list_sandbox_audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/sandbox/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /v1/{admin_api_prefix}/sandbox/jobs` `OpenAPI` stub. */
        post: operations["create_sandbox_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/sandbox/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /v1/{admin_api_prefix}/sandbox/jobs/{id}` `OpenAPI` stub. */
        get: operations["get_sandbox_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/sandbox/jobs/{id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /v1/{admin_api_prefix}/sandbox/jobs/{id}/commit` `OpenAPI` stub. */
        post: operations["commit_sandbox_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{admin_api_prefix}/sandbox/jobs/{id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /v1/{admin_api_prefix}/sandbox/jobs/{id}/discard` `OpenAPI` stub. */
        post: operations["discard_sandbox_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Body for `POST /v1/carts/{id}/lines`.
         * @example {
         *       "quantity": 1,
         *       "variant_id": "33333333-3333-3333-3333-333333333331"
         *     }
         */
        AddCartLineRequest: {
            /**
             * Format: int32
             * @description Quantity greater than zero.
             * @example 1
             */
            quantity: number;
            /**
             * @description Variant to add.
             * @example 33333333-3333-3333-3333-333333333331
             */
            variant_id: string;
        };
        /**
         * @description Where a credential was resolved from (never the secret itself).
         * @enum {string}
         */
        AiCredentialSource: "env" | "default" | "none";
        /** @description One catalog row for the admin UI (no secrets). */
        AiProviderCatalogItem: {
            /** @description Default base URL when known. */
            default_base_url: string;
            /** @description Display label. */
            display_name: string;
            /** @description Env var name for the API key (may be empty). */
            env_api_key: string;
            /** @description Env var name for base URL (may be empty). */
            env_base_url: string;
            /** @description Group. */
            group: string;
            /** @description Stable id. */
            id: string;
            /** @description Protocol kind label. */
            kind: string;
        };
        /** @description Status of one provider after env resolution. */
        AiProviderStatus: {
            /** @description Whether credentials / local URL resolve. */
            available: boolean;
            /** @description Resolved base URL when applicable (no key). */
            base_url?: string | null;
            /** @description Display label. */
            display_name: string;
            /** @description Safe hint (last-4 of key, or host:port for local). Never a full secret. */
            hint?: string | null;
            /** @description Stable id. */
            id: string;
            /** @description Whether this id is the configured default provider. */
            is_default: boolean;
            /** @description Credential source (`env` / `default` / `none`). */
            source: components["schemas"]["AiCredentialSource"];
        };
        /** @description Body for `POST …/ai/providers/test`. */
        AiProviderTestRequest: {
            /** @description Provider id to probe. */
            provider_id: string;
        };
        /** @description Result of a provider connectivity / config test. */
        AiProviderTestResponse: {
            /** @description Error when not ok. */
            error?: string | null;
            /** @description Whether the probe succeeded. */
            ok: boolean;
            /** @description Provider id tested. */
            provider_id: string;
        };
        /** @description List payload for `GET …/ai/providers/catalog`. */
        AiProvidersCatalogResponse: {
            /** @description Static catalog rows. */
            providers: components["schemas"]["AiProviderCatalogItem"][];
        };
        /** @description List payload for `GET …/ai/providers`. */
        AiProvidersStatusResponse: {
            /** @description Default provider id from env (or first available). */
            default_provider_id?: string | null;
            /** @description Status rows in catalog order. */
            providers: components["schemas"]["AiProviderStatus"][];
        };
        /** @description One tool row for agent discovery (shop or admin). */
        AiToolResponse: {
            /** @description Read / draft write / commit (`read` / `draft_write` / `commit`). */
            effect: string;
            /** @description Autonomous agents need human or strict policy approve. */
            human_approve_for_autonomous: boolean;
            /** @description HTTP method for the commerce route. */
            method: string;
            /** @description Stable MCP / agent function name. */
            name: string;
            /** @description Matching `OpenAPI` path template. */
            openapi_path: string;
            /** @description Shop vs admin authz class (`shop` / `admin`). */
            scope: string;
            /** @description One-line capability summary. */
            summary: string;
        };
        /** @description Cart line JSON. */
        CartLineResponse: {
            /** @description Line id. */
            id: string;
            /** @description Line total (`unit_price × quantity`). */
            line_total: components["schemas"]["MoneyResponse"];
            /** @description Snapshotted product name. */
            product_name: string;
            /**
             * Format: int32
             * @description Quantity.
             */
            quantity: number;
            /** @description Snapshotted unit price. */
            unit_price: components["schemas"]["MoneyResponse"];
            /** @description Variant id. */
            variant_id: string;
            /** @description Snapshotted SKU. */
            variant_sku: string;
        };
        /** @description Cart JSON including recalculated totals. */
        CartResponse: {
            /** @description Cart currency. */
            currency: string;
            /** @description Optional customer id. */
            customer_id?: string | null;
            /** @description Cart id. */
            id: string;
            /** @description Sum of line totals. */
            items_total: components["schemas"]["MoneyResponse"];
            /** @description Cart lines. */
            lines: components["schemas"]["CartLineResponse"][];
            /** @description Cart status (`open` or `checked_out`). */
            status: string;
            /** @description Session token. */
            token: string;
        };
        /**
         * @description Body for `POST /v1/checkout`.
         * @example {
         *       "cart_id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
         *     }
         */
        CheckoutRequest: {
            /**
             * @description Cart to convert into an order.
             * @example aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
             */
            cart_id: string;
        };
        /** @description Commit response: updated job + cart snapshot after host apply. */
        CommitSandboxJobResponse: {
            /** @description Cart after host-mediated mutation. */
            cart: components["schemas"]["CartResponse"];
            /** @description Job after commit. */
            job: components["schemas"]["SandboxJobResponse"];
        };
        /**
         * @description Body for `POST /v1/carts`.
         * @example {
         *       "currency": "EUR"
         *     }
         */
        CreateCartRequest: {
            /**
             * @description ISO currency for the cart (default `EUR`).
             * @example EUR
             */
            currency?: string | null;
        };
        /** @description Request body for creating a sandbox job. */
        CreateSandboxJobRequest: {
            /** @description Target cart id for `cart_quantity`. */
            cart_id?: string | null;
            /** @description Cart currency for the quote fixture. */
            currency?: string | null;
            /** @description Job type (`quote` or `cart_quantity`). */
            job_type: string;
            /** @description Cart lines for the quote guest snapshot. */
            lines?: components["schemas"]["SandboxJobLine"][] | null;
            /** @description Operator for `cart_quantity` (`up` / `down` / `set`). */
            operator?: string | null;
            /**
             * Format: int32
             * @description Quantity operand for `cart_quantity`.
             */
            quantity?: number | null;
            /** @description Variant id passed to the migration guest as legacy `id_product`. */
            variant_id?: string | null;
        };
        /** @description JSON error body (message + stable machine code). */
        ErrorBody: {
            /** @description Stable machine-readable code (`not_found`, `conflict`, …). */
            code: string;
            /** @description Human-readable error message. */
            error: string;
        };
        /** @description JSON body for `GET /healthz`. */
        HealthResponse: {
            /** @description Serenade kernel integration marker from the `rustashop` crate (`serenade` after boot). */
            kernel: string;
            /** @description Liveness status. */
            status: string;
        };
        /**
         * @description Money JSON for cart responses.
         * @example {
         *       "amount_minor": 4500,
         *       "currency": "EUR"
         *     }
         */
        MoneyResponse: {
            /**
             * Format: int64
             * @description Amount in minor units.
             * @example 4500
             */
            amount_minor: number;
            /**
             * @description ISO currency code.
             * @example EUR
             */
            currency: string;
        };
        /** @description Order line JSON. */
        OrderLineResponse: {
            /** @description Line id. */
            id: string;
            /** @description Snapshotted line total. */
            line_total: components["schemas"]["MoneyResponse"];
            /** @description Snapshotted product name. */
            product_name: string;
            /**
             * Format: int32
             * @description Quantity.
             */
            quantity: number;
            /** @description Snapshotted unit price. */
            unit_price: components["schemas"]["MoneyResponse"];
            /** @description Variant id when still known. */
            variant_id?: string | null;
            /** @description Snapshotted SKU. */
            variant_sku: string;
        };
        /** @description Paginated admin order list. */
        OrderListResponse: {
            /** @description Orders newest first. */
            items: components["schemas"]["OrderResponse"][];
        };
        /** @description Order JSON returned by checkout. */
        OrderResponse: {
            /** @description Source cart id. */
            cart_id?: string | null;
            /** @description Order currency. */
            currency: string;
            /** @description Order id. */
            id: string;
            /** @description Sum of line totals. */
            items_total: components["schemas"]["MoneyResponse"];
            /** @description Order lines. */
            lines: components["schemas"]["OrderLineResponse"][];
            /** @description Human-readable number. */
            number: string;
            /** @description Payment status (`pending` at checkout; no provider attached yet). */
            payment_status: string;
            /** @description Fulfillment state. */
            state: string;
            /** @description Payable total. */
            total: components["schemas"]["MoneyResponse"];
        };
        /**
         * @description Body for admin order status PATCH.
         * @example {
         *       "status": "shipped"
         *     }
         */
        PatchOrderStatusRequest: {
            /**
             * @description Fulfillment status: `placed`, `paid`, `shipped`, or `cancelled`.
             * @example shipped
             */
            status: string;
        };
        /** @description Product detail including purchasable variants. */
        ProductDetailResponse: {
            /** @description Optional category id. */
            category_id?: string | null;
            /** @description Optional long description. */
            description?: string | null;
            /** @description Whether the product is offered for sale. */
            enabled: boolean;
            /** @description Stable identifier. */
            id: string;
            /** @description Display name. */
            name: string;
            /** @description Unique URL slug. */
            slug: string;
            /** @description Purchasable SKUs for this product. */
            variants: components["schemas"]["ProductVariantResponse"][];
        };
        /** @description List payload for `GET /v1/products`. */
        ProductListResponse: {
            /** @description Page of products. */
            items: components["schemas"]["ProductResponse"][];
        };
        /**
         * @description Product JSON returned by list routes (no variants).
         * @example {
         *       "category_id": "11111111-1111-1111-1111-111111111111",
         *       "description": "Soft cotton hoodie",
         *       "enabled": true,
         *       "id": "22222222-2222-2222-2222-222222222221",
         *       "name": "Hoodie",
         *       "slug": "hoodie"
         *     }
         */
        ProductResponse: {
            /** @description Optional category id. */
            category_id?: string | null;
            /** @description Optional long description. */
            description?: string | null;
            /**
             * @description Whether the product is offered for sale.
             * @example true
             */
            enabled: boolean;
            /**
             * @description Stable identifier.
             * @example 22222222-2222-2222-2222-222222222221
             */
            id: string;
            /**
             * @description Display name.
             * @example Hoodie
             */
            name: string;
            /**
             * @description Unique URL slug.
             * @example hoodie
             */
            slug: string;
        };
        /** @description Variant JSON nested under product detail. */
        ProductVariantResponse: {
            /** @description Stable identifier. */
            id: string;
            /** @description Optional variant label. */
            name?: string | null;
            /** @description Unit price. */
            price: components["schemas"]["MoneyResponse"];
            /** @description Parent product id. */
            product_id: string;
            /** @description Unique stock-keeping unit. */
            sku: string;
            /**
             * Format: int32
             * @description Available stock quantity.
             */
            stock_quantity: number;
        };
        /** @description Adjustment JSON for admin. */
        SandboxAdjustmentResponse: {
            /**
             * Format: int64
             * @description Signed minor units.
             */
            amount_minor: number;
            /** @description Currency. */
            currency: string;
            /** @description Label. */
            label: string;
        };
        /** @description One audit row (process-local until a persist table lands). */
        SandboxAuditRecord: {
            /** @description Actor label (`admin-bearer` when authorized). */
            actor: string;
            /**
             * Format: int64
             * @description Unix seconds when the job was created.
             */
            created_at_unix: number;
            /** @description Job id. */
            job_id: string;
            /** @description Job type. */
            job_type: string;
            /** @description Source fingerprint. */
            source_hash: string;
            /** @description Final status string. */
            status: string;
        };
        /** @description One cart line in the create-job body. */
        SandboxJobLine: {
            /**
             * Format: int32
             * @description Quantity.
             */
            quantity: number;
            /** @description SKU. */
            sku: string;
            /**
             * Format: int64
             * @description Unit price in minor units.
             */
            unit_price_minor: number;
        };
        /** @description Public job view. */
        SandboxJobResponse: {
            /** @description Host-validated adjustments when quote succeeded. */
            adjustments?: components["schemas"]["SandboxAdjustmentResponse"][] | null;
            /** @description Error message when failed. */
            error?: string | null;
            /** @description Job id. */
            id: string;
            /** @description Job type. */
            job_type: string;
            proposal?: null | components["schemas"]["SandboxProposalResponse"];
            /** @description Fingerprint of the fixture source used. */
            source_hash: string;
            /** @description Lifecycle status. */
            status: components["schemas"]["SandboxJobStatus"];
        };
        /**
         * @description Job status returned to the admin UI.
         * @enum {string}
         */
        SandboxJobStatus: "running" | "succeeded" | "awaiting_commit" | "committed" | "discarded" | "failed";
        /** @description Validated domain-event proposal awaiting host commit. */
        SandboxProposalResponse: {
            /** @description Target cart id. */
            cart_id: string;
            /** @description Domain event type. */
            event_type: string;
            /** @description Operator (`up` / `down` / `set`). */
            operator: string;
            /** @description Variant id (legacy `id_product` in the guest ABI). */
            product_id: string;
            /**
             * Format: int32
             * @description Quantity operand.
             */
            quantity: number;
        };
        /**
         * @description Body for `PATCH /v1/carts/{id}/lines/{line_id}`.
         * @example {
         *       "quantity": 2
         *     }
         */
        UpdateCartLineRequest: {
            /**
             * Format: int32
             * @description Replacement quantity greater than zero.
             * @example 2
             */
            quantity: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "kernel": "serenade",
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    openapi_json: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_shop_ai_tools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shop-scoped commerce AI tool catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiToolResponse"][];
                };
            };
        };
    };
    create_cart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCartRequest"];
            };
        };
        responses: {
            /** @description Cart created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "currency": "EUR",
                     *       "customer_id": null,
                     *       "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                     *       "items_total": {
                     *         "amount_minor": 0,
                     *         "currency": "EUR"
                     *       },
                     *       "lines": [],
                     *       "status": "open",
                     *       "token": "cart-token-example"
                     *     }
                     */
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Invalid currency */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_cart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cart id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Unknown id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    add_cart_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cart id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCartLineRequest"];
            };
        };
        responses: {
            /** @description Cart after add */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Unknown cart or variant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid quantity or currency */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_cart_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cart id */
                id: string;
                /** @description Line id */
                line_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart after delete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Unknown cart or line */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_cart_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cart id */
                id: string;
                /** @description Line id */
                line_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartLineRequest"];
            };
        };
        responses: {
            /** @description Cart after update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Unknown cart or line */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid quantity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    place_order: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replay token */
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Order placed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "cart_id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                     *       "currency": "EUR",
                     *       "id": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
                     *       "items_total": {
                     *         "amount_minor": 4500,
                     *         "currency": "EUR"
                     *       },
                     *       "lines": [
                     *         {
                     *           "id": "cccccccc-cccc-cccc-cccc-cccccccccccc",
                     *           "line_total": {
                     *             "amount_minor": 4500,
                     *             "currency": "EUR"
                     *           },
                     *           "product_name": "Hoodie",
                     *           "quantity": 1,
                     *           "unit_price": {
                     *             "amount_minor": 4500,
                     *             "currency": "EUR"
                     *           },
                     *           "variant_id": "33333333-3333-3333-3333-333333333331",
                     *           "variant_sku": "HOODIE-S"
                     *         }
                     *       ],
                     *       "number": "RS-1001",
                     *       "payment_status": "pending",
                     *       "state": "placed",
                     *       "total": {
                     *         "amount_minor": 4500,
                     *         "currency": "EUR"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Unknown cart */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Cart already checked out */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Empty cart */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_products: {
        parameters: {
            query?: {
                /** @description Maximum rows (capped). */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "category_id": "11111111-1111-1111-1111-111111111111",
                     *           "description": "Soft cotton hoodie",
                     *           "enabled": true,
                     *           "id": "22222222-2222-2222-2222-222222222221",
                     *           "name": "Hoodie",
                     *           "slug": "hoodie"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
        };
    };
    get_product: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product with variants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "category_id": "11111111-1111-1111-1111-111111111111",
                     *       "description": "Soft cotton hoodie",
                     *       "enabled": true,
                     *       "id": "22222222-2222-2222-2222-222222222221",
                     *       "name": "Hoodie",
                     *       "slug": "hoodie",
                     *       "variants": [
                     *         {
                     *           "id": "33333333-3333-3333-3333-333333333331",
                     *           "name": "Small",
                     *           "price": {
                     *             "amount_minor": 4500,
                     *             "currency": "EUR"
                     *           },
                     *           "product_id": "22222222-2222-2222-2222-222222222221",
                     *           "sku": "HOODIE-S",
                     *           "stock_quantity": 10
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ProductDetailResponse"];
                };
            };
            /** @description Unknown id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_ai_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model provider status (masked) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiProvidersStatusResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_ai_providers_catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model provider catalog (env names only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiProvidersCatalogResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    test_ai_provider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiProviderTestRequest"];
            };
        };
        responses: {
            /** @description Provider probe result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiProviderTestResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_ai_tools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commerce AI tool catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiToolResponse"][];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_admin_orders: {
        parameters: {
            query?: {
                /** @description Maximum rows (capped). */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    patch_admin_order: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Order id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchOrderStatusRequest"];
            };
        };
        responses: {
            /** @description Updated order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid status */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_admin_products: {
        parameters: {
            query?: {
                /** @description Maximum rows (capped). */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_sandbox_audit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit rows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxAuditRecord"][];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_sandbox_job: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSandboxJobRequest"];
            };
        };
        responses: {
            /** @description Job accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxJobResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_sandbox_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxJobResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unknown job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    commit_sandbox_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Committed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitSandboxJobResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unknown job or cart line */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not awaiting commit */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    discard_sandbox_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discarded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxJobResponse"];
                };
            };
            /** @description Missing or invalid bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unknown job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not awaiting commit */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
