/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /healthz` handler. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /openapi.json` handler. */
        get: operations["openapi_json"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates an empty cart. */
        post: operations["create_cart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns one cart by id. */
        get: operations["get_cart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/{id}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adds a line (merges quantity when the variant is already present). */
        post: operations["add_cart_line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carts/{id}/lines/{line_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Removes a line. */
        delete: operations["delete_cart_line"];
        options?: never;
        head?: never;
        /** Updates a line quantity. */
        patch: operations["update_cart_line"];
        trace?: never;
    };
    "/v1/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Converts a cart into a placed order. */
        post: operations["place_order"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists enabled products. */
        get: operations["list_products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns one product by id. */
        get: operations["get_product"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Body for `POST /v1/carts/{id}/lines`. */
        AddCartLineRequest: {
            /**
             * Format: int32
             * @description Quantity greater than zero.
             */
            quantity: number;
            /** @description Variant to add. */
            variant_id: string;
        };
        /** @description Cart line JSON. */
        CartLineResponse: {
            /** @description Line id. */
            id: string;
            /** @description Line total (`unit_price × quantity`). */
            line_total: components["schemas"]["MoneyResponse"];
            /** @description Snapshotted product name. */
            product_name: string;
            /**
             * Format: int32
             * @description Quantity.
             */
            quantity: number;
            /** @description Snapshotted unit price. */
            unit_price: components["schemas"]["MoneyResponse"];
            /** @description Variant id. */
            variant_id: string;
            /** @description Snapshotted SKU. */
            variant_sku: string;
        };
        /** @description Cart JSON including recalculated totals. */
        CartResponse: {
            /** @description Cart currency. */
            currency: string;
            /** @description Optional customer id. */
            customer_id?: string | null;
            /** @description Cart id. */
            id: string;
            /** @description Sum of line totals. */
            items_total: components["schemas"]["MoneyResponse"];
            /** @description Cart lines. */
            lines: components["schemas"]["CartLineResponse"][];
            /** @description Cart status (`open` or `checked_out`). */
            status: string;
            /** @description Session token. */
            token: string;
        };
        /** @description Body for `POST /v1/checkout`. */
        CheckoutRequest: {
            /** @description Cart to convert into an order. */
            cart_id: string;
        };
        /** @description Body for `POST /v1/carts`. */
        CreateCartRequest: {
            /** @description ISO currency for the cart (default `EUR`). */
            currency?: string | null;
        };
        /** @description JSON error body. */
        ErrorBody: {
            /** @description Machine-readable error. */
            error: string;
        };
        /** @description JSON body for `GET /healthz`. */
        HealthResponse: {
            /** @description Liveness status. */
            status: string;
        };
        /** @description Money JSON for cart responses. */
        MoneyResponse: {
            /**
             * Format: int64
             * @description Amount in minor units.
             */
            amount_minor: number;
            /** @description ISO currency code. */
            currency: string;
        };
        /** @description Order line JSON. */
        OrderLineResponse: {
            /** @description Line id. */
            id: string;
            /** @description Snapshotted line total. */
            line_total: components["schemas"]["MoneyResponse"];
            /** @description Snapshotted product name. */
            product_name: string;
            /**
             * Format: int32
             * @description Quantity.
             */
            quantity: number;
            /** @description Snapshotted unit price. */
            unit_price: components["schemas"]["MoneyResponse"];
            /** @description Variant id when still known. */
            variant_id?: string | null;
            /** @description Snapshotted SKU. */
            variant_sku: string;
        };
        /** @description Order JSON returned by checkout. */
        OrderResponse: {
            /** @description Source cart id. */
            cart_id?: string | null;
            /** @description Order currency. */
            currency: string;
            /** @description Order id. */
            id: string;
            /** @description Sum of line totals. */
            items_total: components["schemas"]["MoneyResponse"];
            /** @description Order lines. */
            lines: components["schemas"]["OrderLineResponse"][];
            /** @description Human-readable number. */
            number: string;
            /** @description Payment stub (`pending` until a PSP is wired). */
            payment_status: string;
            /** @description Fulfillment state. */
            state: string;
            /** @description Payable total. */
            total: components["schemas"]["MoneyResponse"];
        };
        /** @description List payload for `GET /v1/products`. */
        ProductListResponse: {
            /** @description Page of products. */
            items: components["schemas"]["ProductResponse"][];
        };
        /** @description Product JSON returned by catalog routes. */
        ProductResponse: {
            /** @description Optional category id. */
            category_id?: string | null;
            /** @description Optional long description. */
            description?: string | null;
            /** @description Whether the product is offered for sale. */
            enabled: boolean;
            /** @description Stable identifier. */
            id: string;
            /** @description Display name. */
            name: string;
            /** @description Unique URL slug. */
            slug: string;
        };
        /** @description Body for `PATCH /v1/carts/{id}/lines/{line_id}`. */
        UpdateCartLineRequest: {
            /**
             * Format: int32
             * @description Replacement quantity greater than zero.
             */
            quantity: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    openapi_json: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_cart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCartRequest"];
            };
        };
        responses: {
            /** @description Cart created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Invalid currency */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_cart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cart id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Unknown id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    add_cart_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cart id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCartLineRequest"];
            };
        };
        responses: {
            /** @description Cart after add */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Unknown cart or variant */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid quantity or currency */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_cart_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cart id */
                id: string;
                /** @description Line id */
                line_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart after delete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Unknown cart or line */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_cart_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cart id */
                id: string;
                /** @description Line id */
                line_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartLineRequest"];
            };
        };
        responses: {
            /** @description Cart after update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Unknown cart or line */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid quantity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    place_order: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replay token */
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Order placed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Unknown cart */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Cart already checked out */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Empty cart */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_products: {
        parameters: {
            query?: {
                /** @description Maximum rows (capped). */
                limit?: number | null;
                /** @description Rows to skip. */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
        };
    };
    get_product: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Unknown id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
